class resep {
  String id;
  String makanan;
  String alatdanbahan;

  resep({
    required this.id,
    required this.makanan,
    required this.alatdanbahan,
  });
}

List resepList = [
  resep(
        id: "buburmanado",
        makanan: "Bubur Manado",
        alatdanbahan:
               "Bahan:-200 gram beras.2 buah jagung manis dipipil.150 gram singkong potong dadu.- 100 gram ubi kuning, potong dadu .- 1 kg labu kuning, kukus dan lumatkan dengan garpu.- 4 liter air atau tambahkan sesuai kebutuhan.Bahan sayur:- 5 lembar daun gedi,rajang halus .- 1 lembar daun kunyit,rajang sehalus mungkin.- 2 batang daun bawang, rajang halus.- 1 ikat kangkung, ambil daun dan pucuk mudanya, rajang kasar- 1 ikat kecil bayam, ambil daun.- 1 mangkuk kemangi, dari 5 ikat kecil kemangi, ambil daun dan pucuk mudanya saja. Bumbu:- 5 batang serai, ambil bagian putihnya saja dan memarkan.- 2 lembar daun salam.- 1 sdm garam.- kaldu jamur secukupnya.- 6 bawang putih, cincang halus.- 6 bawang merah iris tipis.Bumbu pelengkap- sambal dabu dabu atau sambal korek.- ikan asin goreng. Cara memasak :a. Cuci bersih beras,lalu di panci masukkan air, beras, singkong, ubi masak dengan api kecil sampai singkong dan ubi lembut.b. Masukkan bawang putih, bawang merah, daun salam dan serai sambil terus diaduk, masukkan jagung dan labu kuning.c. Tambahkan air bila diperlukan, masukkan garam lada dan kaldu jamur aduk rata lagi.d. Setelah beras sudah menjadi bubur terakhir masukan semua sayuran aduk rata, koreksi rasa, angkat.3. Sop Konro.Bahan :-1kg iga sapi.-1700 ml air.-1/2butir kelapa parut kemudian disangrai hingga kering lalu dihaluskan.-1lembar daun salam.-2lembar daun jeruk.-2cm kayu manis.- Daun bawang dan Daun Seledri secukupnya.- Minyak secukupnya untuk menumis.- Gula pasir,garam,kaldu sapi bubuk secukupnya.Bumbu halus :- 10 siung bawang merah.- 6 siung bawang putih.- 4 butir kemiri.- 1 buah kluwak.- 5 batang sereh.- Serimpang lengkuas.- 2 cm kunyit.- 1/2 sdt merica bubuk.- 1 sdt jinten bubuk.- 1 sdt ketumbar bubuk.- 1/4 pala bubuk.Bahan pelengkap :- Nasi putih atau buras. - Bawang goreng. - Sambel & jeruk nipis.Cara memasak :a. Presto iga sapi hingga empuk dengan air secukupnya,saring ambil kaldunya 1 liter.b. Pindahkan kepanci biasa,masukan iga dan kaldunya lalu tambah air biasa 700 ml atau secukupnya.c. Tumis bumbu halus dengan minyak secukupnya hingga wangi,lalu masukan kedalam panci iga,masukan juga daun salam,daun jeruk,kayu manis dan kelapa sangrai yang dihaluskan,aduk rata,beri gula garam dan kaldu sapi bubuk,didihkan cek rasa.d. Masukan potongan daun seledri dan daun bawang secukupnya didihkan sebentar matikan api.e. Sajikan dimangkok saji lalu taburi bawang goreng."),
  resep(
      id: "candilketan",
      makanan: "Candil Ketan",
      alatdanbahan:
                 "Bahan :- 200 gr tepung ketan.- 30 g tepung tapioka. Tepung beras atau boleh tepung ketan saja.- 1/3 sdt garam.- secukupnya air hangat sampai adonan bisa dipulung.Bahan kuah :- 150 gula merah, disisir.- 800 ml air. - 2 lembar daun pandan ditali simpul.Bahan larutan pengental :- 1 sdm tepung ketan atau boleh lebih jika suka kuah yang kental.- 1 sdm tepung beras atau boleh lebih jika suka kuah yang kental.- Campur semua bahan dan tambahkan sedikit air, aduk hingga larut dan tidak ada yang bergerindil.Bahan kuah santan :- 400 ml santan kental.- 1/4 sdt garam.- Secukupnya buah nangka dipotong kotak kecil2 ( opsional).Rebus kuah santan hingga mendidih bersama garam dan daun pandan. Matikan api. Masukan potongan nangka.Cara memasak : a. Campur tepung ketan, tepung tapioka dan garam, tuangi air hangat secukupnya sampai adonan lembut dan enak buat dipulung ( kalau terlalu lembek boleh ditambahi tepung ketan lagi).b.Siapkan nampan, taburi tipis2 dengan tepung kanji.c.Ambil secuil adonan bentuk bulat sebesar kelereng. Susun di atas nampan. Lakukan sampai adonan habisd. Masak semua bahan kuah kuah gula merah hingga gula larut dan mendidih.e. Saring lalu masak lagi sampai mendidih.f. Masukkan bola bola ketan. Masak dengan api kecil hingga gula meresap dan warna bola bola ketan berubah kecoklatan.g. Masukkan larutan tepung , aduk pelan sampai kental dan meletup2.h. Jika kurang kental bisa ditambahkan tepung ketan/ tepung beras yang dicairkan lalu dimasak lagi sampai kental.i. Sajikan dengan kuah santan.6. Pempek PalembangBahan untuk biang : - 400 ml air.- 200 gr terigu.- Secukupnya Garam dan gula.Bahan untuk adonan pempek-3.butir telur dikocok dicampur ke dalam adonan pempek.- 5 siung bawang putih dihaluskan.- 400 gr sagu tani.Bahan untuk isian :- 2 butir telur dikocok beri garam, gula sedikitCara memasak :a. Dalam panci campur terigu, air, garam dan gula. Aduk rata. Nyalakan api, masak sambil diaduk-aduk sampai menggumpal seperti bubur (hati-hati gosong) Angkat. Biarkan hangat.b. Pindahkan biang yang sudah tidak panas ke dalam baskom. Dalam keadaan hangat tambahkan bawang putih, telur kocok. Aduk rata pakai sendok kayu.c. Masukkan sagu sedikit-sedikit. Aduk rata.d. Balur tangan dengan sagu, ambil sebagian adonan bentuk silindere.Buat lubang dengan menggunakan jari telunjuk. Bentuk seperti contong kemudian isi dengan telur kocokf. Tutup adonan pempek rapat-rapat supaya tidak terbuka pada saat direbusg. Rebus pempek dalam air mendidih sampai matang, angkat."),
  
  resep(
      id: "nasibakepor",
      makanan: "Nasi Bakepor Kalimantan Timur",
      alatdanbahan:
          "Bahan :-300 gr beras putih, cuci bersih- 2 lembar daun salam- 1 lembar daun pandan, poton- 4 sdm minyak sayur- 1 sdt garam- 400 ml air- 75 gr ikan asin gabus, goreng, lalu suwir - suwir- 15 lembar daun kemangi- 3 buah cabe rawit, iris bulat tipis.-1/2 buah jeruk nipis, ambil airnyaSambal Raja :- 1 buah terong, potong dadu 1 cm- 10 lonjor kacang panjang, potong 2 cm- 10 siung bawang merah, belah 4Bumbu halus :- 10 buah cabe rawit- 10 buah cabe merah besar, buang biji- 2 buah jeruk limau- 1 bks kecil terasi- 1 sdt garam- 1 sdm gula pasirCara memasak :a. Goreng ikan asin gabus. Angkat. Tiriskan. Suwir - suwir. Sisihkanb. Nasi Bakepor : Siapkan panci tebal. Masukkan ke dalamnya beras, air, minyak, daun salam, daun pandan, dan garam.c. Masak di atas api kecil sambil diaduk. Angkat.d. Masukkan daun kemangi, ikan asin suwir, cabai, dan air jeruk nipis, aduk rata.e. Tutup panci kemudian Masak dengan api sangat kecil hingga tanak dan nasi matang.f. Buka tutup panci biarkan hingga permukaan nasi tampak kering dan bagian pinggirnya berkerak. Matikan api.g. Sambal Raja : Goreng kacang panjang, terong dan bawang merah sebentar dengan minyak panas.Tiriskan.h. Ulek cabe rawit, cabe merah, terasi, garam dan gula pasir. Beri perasan jeruk limau.(Kulit jeruk jangan di buang, iris halus kulit jeruk).i. Tumis sambal hingga harum, masukkan kacang panjang, terong dan bawang merah yang telah di goreng tadi.j. Aduk rata sebelum di angkat masukkan irisan kulit jeruk limau. Aduk rata. Matikan api.k. Sambal Raja siap di dampingkan dengan nasi bakeporh. Penyajian : Hidangkan Nasi Bakepor hangat hangat dengan sambal Raja."),
  resep(
      id: "rawonsurabaya",
      makanan: "Rawon Surabaya",
      alatdanbahan:
          "Bahan:- 500 gram daging sapi, bagian sandung lumur- Air untuk merebus daging- 1.500 ml air kaldu sapi- 3 sdm minyak goreng, untuk menumis- 1 sdm garamHaluskan:- 6 siung bawang putih- 4 biji keluak (ambil isinya, lalu rendam dalam air)- 8 buah cabai merah- 2 ibu jari lengkuas- 3 cm kunyit- 2 cm kencur- 2 cm jahe- 2 sdm ketumbar- 1/4 sdt jintan- 1/2 sdt merica butir- 4 lembar daun salam- 2 batang serai, memarkan- 2 mata asam jawa, larutkan dengan 1 sdm air- 5 lembar daun jeruk purutPelengkap:- Tauge pendek/kecambah- Telur bebek asin- Sambal terasi- Kerupuk ikanCara memasak :a. Cuci daging sampai bersih, rebus sampai matang. Angkat dan tiriskan daging, lalu potong ukuran dadu. Sisihkan daging dan air kaldunya.b. Panaskan minyak, tumis bumbu halus sampai harum dan matang. Masukkan daging, serai, daun jeruk, air asam, dan garam. Aduk sampai rata dan beraroma. c. Pukul-pukul daging sampai melebar. Goreng dalam minyak panas sebentar, angkat. Taburi dengan bawang goreng"),
  resep(
      id: "seblakbandung",
      makanan: "Seblak Bandung",
      alatdanbahan:
          "Bahan:- 2 genggam kerupuk (redam di air biasa 2 jam).- 6 butir bakso.- 200 g ceker.Bumbu halus:- 4 siung bawang merah.- 3 siung bawang putih.- 3 butir kemiri(boleh di kurangi klo ga suka creamy).- 1 ruas jari kencur.- 8 cabe merah keriting.- 6 cabe rawit pedas. - 5 cabe rawit hijau (untuk irisan). - Gula, garam, kaldu bubuk, lada bubuk.- 1 bonggol sawi sendok.- 1 batang daun bawang.- Air kaldubrebusan ceker (sesuai selera).- 2 butir telur yang sudah di orak arik.Cara memasak :a. Tumis bumbu hingga matang.b. Tambahkan bakso, ceker, kerupuk yg sudah di rendam, garam, gula, lada, saus tiram, kaldu bubuk. Masak sebentar.c. Tambah air kaldu, masak hingga mendidih.d. Masukkan daun sawi, daun bawang, dan cabe rawit iris, masak hingga sayuran matang.s"),
  resep(
      id: "sotopadang",
      makanan: "Soto Padang",
      alatdanbahan:
      "Bahan :- 500 gram daging sapi (campur dengan tulang supaya kaldunya lebih kerasa).- 2 liter air.- minyak goreng untuk menumis. Bahan cemplung :- 2 batang sereh digeprek.- 3 lembar daun salam.- 4 lembar daun jeruk.- 5 buah kapulaga.- 8 kelopak bunga lawang.- 5 buah cengkeh.- 4 cm kayu manis.- 2 batang daun bawang diiris.Bumbu halus :- 10 siung bawang putih.- 6 buah bawang merah.- 3 ruas lengkuas.- 2 ruas jahe. - 1 ruas kunyi. - 1 sdt pala bubuk.- 1 sdm ketumbar bubuk.- 2 sdt lada bubuk.- garam. Bumbu pelengkap :- sohun siram dengan air panas, rendam sebentar, angkat dan tiriskan.- perkedel kentang. - kerupuk merah. - sambal.- seledri diiris halus.- bawang goreng. - kecap.- cuka.Cara memasak :a. Rebus daging sampai mendidih keluar buihnya, buah buih yang mengapung, masukkan semua bahan cemplung, lanjutkan merebus sampai daging empuk, masukan daun bawang, tunggu layu, matikan kompor, angkat daging, dan tunggu dingin. b. Panaskan minyak goreng, tumis bumbu halus sampai wangi, campur bumbu yang sudah ditumis ke dalam air rebusan daging, masak sebentar sampai bumbu dan kaldu menyatu. koreksi rasa. c. Iris tipis daging yang sudah direbus, kemudian goreng sampai garing.d. Tata sohun, daging didalam mangkok, siram dengan kuah soto, beri kerupuk, perkedel, seledri dan sambal. e. Sajikan."),
];
